apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/AcmeCorp/devops-configs.git
      targetRevision: main
      path: .
      ref: values
    - repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      chart: aws-ebs-csi-driver
      targetRevision: 2.53.0
      helm:
        releaseName: ebs-csi-controller
        valueFiles:
          - $values/values/infra/ebs-csi-controller/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
