apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: datadog-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: eks/acme-main-dev
        property: DATADOG_API_KEY
