apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: company-items
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: n7xQ2mL9pR4v
  POSTGRES_PASSWORD: wK8!rT2mN4xP9qL6
  POSTGRES_DB: company_items

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: company-items
  labels:
    app: backend
type: Opaque
stringData:
  DB_USER: n7xQ2mL9pR4v
  DB_PASSWORD: wK8!rT2mN4xP9qL6
