apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/AcmeCorp/devops-configs.git
      targetRevision: main
      ref: values
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 0.47.4
      helm:
        releaseName: argo-workflows
        valueFiles:
          - $values/values/infra/argo-workflows/prd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Argo Workflows - workflow engine for Kubernetes (prd)"
