apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mall-v3-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=111111111111.dkr.ecr.ap-northeast-2.amazonaws.com/acmemall-backend-dev
    argocd-image-updater.argoproj.io/app.pull-secret: ext:/scripts/ecr.sh
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.platforms: linux/amd64
spec:
  project: mall
  source:
    repoURL: https://github.com/AcmeCorp/devops-configs.git
    targetRevision: main
    path: charts/app
    helm:
      valueFiles:
        - ../../values/apps/mall/v3/api/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
