apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: eks/acme-main-v2-prd
        property: authentik_SECRET_KEY
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: eks/acme-main-v2-prd
        property: authentik_PG_PASSWORD
    - secretKey: AUTHENTIK_GOOGLE_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: authentik_GOOGLE_OAUTH_SECRET
    - secretKey: AUTHENTIK_ARGOCD_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: argocd_oidc_authentik_client_secret
    - secretKey: AUTHENTIK_GRAFANA_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: argocd_oidc_authentik_client_secret
    - secretKey: AUTHENTIK_AIRFLOW_GREEN_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: airflow_green_oidc_authentik_client_secret
    - secretKey: AUTHENTIK_ARGO_WORKFLOWS_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: argo_workflows_sso_client_secret
    - secretKey: AUTHENTIK_KUBECOST_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: kubecost_oauth2_client_secret
    - secretKey: AUTHENTIK_OUTLINE_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: outline_oidc_client_secret
    - secretKey: AUTHENTIK_PLANE_DEV_OAUTH_SECRET
      remoteRef:
        key: eks/acme-main-v2-prd
        property: plane_dev_oidc_client_secret
    # PostgreSQL subchart용 (key 이름이 password여야 함)
    - secretKey: password
      remoteRef:
        key: eks/acme-main-v2-prd
        property: authentik_PG_PASSWORD
