{{- if .Values.serviceAccount.create }}
{{- $saName := include "app.serviceAccountName" . }}
{{- $existingSA := lookup "v1" "ServiceAccount" .Release.Namespace $saName }}
{{- if not $existingSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  {{- if .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
