# Airflow Aurora 마스터 크레덴셜 - DB 초기화 Job 전용
# AWS Managed Secret: rds!cluster-00000000-0000-4000-8000-000000000011
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-rds-master
  namespace: outline
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: airflow-rds-master
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:222222222222:secret:rds!cluster-00000000-0000-4000-8000-000000000011-iPJJQr"
        property: username
    - secretKey: password
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:222222222222:secret:rds!cluster-00000000-0000-4000-8000-000000000011-iPJJQr"
        property: password
