apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: venue
  namespace: argocd
spec:
  description: venue
  sourceRepos:
    - "*"
  destinations:
    - namespace: venue
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
