apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-green-dags-pvc
  namespace: airflow-green
  labels:
    name: airflow-green
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
